name: Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build2
    uses: ./.github/workflows/build.yaml

  deploy:
    if: github.event_name == 'push'
    name: Deploy2
    needs: build
    uses: ./.github/workflows/deploy.yaml

  SonarQube:
    name: SonarQube2
    needs: build
    uses: ./.github/workflows/sonarqube.yaml
