name: CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    name: "Build"
    steps:
      - name: Say hi
        run: echo hello

  sonarqube:
    name: SonarQube
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/sonarqube.yml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
    with:
      python_version: ${{ env.PYTHON_VERSION }}
      srcs_paths: "src/"
    needs: build
