name: CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    name: "Build"
    steps:
      - name: Say hi
        run: echo hello > coverage.xml

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: coverage.xml
          if-no-files-found: error
          retention-days:
          overwrite: true

  sonarqube:
    name: SonarQube
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/sonarqube.yml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
    with:
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
      python_version: ${{ vars.PYTHON_VERSION }}
      coverage_name: coverage_report
      srcs_paths: "src/"            # Optional
      tests_path: "tests/"          # Optional
    needs: build
