name: Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  Build:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/build.yaml

  SonarQube:
    permissions:
      contents: read
      actions: read
    needs: Build
    uses: ./.github/workflows/sonarqube.yaml

  Deploy:
    if: github.event_name == 'push'
    needs: [Build,SonarQube]
    uses: ./.github/workflows/deploy.yaml
