name: CI + CD to DEV

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    name: "Build"
    steps:
      - name: Echo & Sleep
        run: echo 12345; sleep 10
