name: SonarQube_Static_Testing

on:
  # workflow_run:
  #   workflows: [CI/CD]
  #   types: [completed]
  schedule:
    - cron: '0 16 * * 0' # Every sunday at 16:00
  workflow_dispatch:
  workflow_call:

jobs:
  scan:
    name: SonarQube Static Testing
    runs-on: ubuntu-latest
    steps:
      - name: Echo & Sleep
        run: echo Scanning...; sleep 7
  analysis:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: Echo & Sleep
        run: echo Analyzing new code...; sleep 7
